# This file was generated by GoReleaser. DO NOT EDIT.
class Rudder < Formula
  desc "Portable Kubernetes deployment tool"
  homepage "github.com/ryantking/rudder"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-darwin-amd64.tar.gz"
    sha256 "ef5165bf21ffe8440e4eb4ab0306b137b7ae64f1801ff1ede812ba0f1533e137"
  elsif OS.linux?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-linux-amd64.tar.gz"
    sha256 "c77f388bfcaa2cb1609d32c47534df04b2439d8469e6f5cbeaede8457ce450b3"
  end

  def install
    bin.install "rudder"
  end

  test do
    system "${bin}/rudder --version"
  end
end
