# This file was generated by GoReleaser. DO NOT EDIT.
class Rudder < Formula
  desc "Portable Kubernetes deployment tool"
  homepage "github.com/ryantking/rudder"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-darwin-amd64.tar.gz"
    sha256 "8799ca3c5b13bddda7d6fef6adc9b230b1d5db949a9d7c841633dcd4e30fb3cc"
  elsif OS.linux?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-linux-amd64.tar.gz"
    sha256 "c4e7531afc2038047986d748446c343caec240a0bdad45f2bf94eedf4e00d970"
  end

  def install
    bin.install "rudder"
  end

  test do
    system "${bin}/rudder --version"
  end
end
