# This file was generated by GoReleaser. DO NOT EDIT.
class Rudder < Formula
  desc "Portable Kubernetes deployment tool"
  homepage "github.com/ryantking/rudder"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-darwin-amd64.tar.gz"
    sha256 "1d6acdba629bac132a437b189e96a8fc248785d15d109906fe85519cff8ac716"
  elsif OS.linux?
    url "https://github.com/ryantking/rudder/releases/download/v1.0.0/rudder-1.0.0-linux-amd64.tar.gz"
    sha256 "ebf5029ec7664473005453989ea50a253abd47665c8cc4333ed490efb316f08e"
  end

  def install
    bin.install "rudder"
  end

  test do
    system "${bin}/rudder --version"
  end
end
